# Working with Tensors

### Install Required libraries

In [33]:
#!pip install torch

In [34]:
import torch
import numpy as np

### playing with Tensors in PyTorch.

In [35]:
# Create Tensor From Data(List)
data = [[1,2], [3,4]]
tensors = torch.tensor(data)

tensors


tensor([[1, 2],
        [3, 4]])

##### Create from NumPy

In [36]:
np_array = np.arange(10)
tensor_np = torch.from_numpy(np_array)

tensor_np

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

#### Shape, ndim and dtype

In [37]:
tensor_np.shape, tensors.shape

(torch.Size([10]), torch.Size([2, 2]))

In [38]:
tensor_np.ndim

1

In [39]:
tensor_np.dtype, tensors.dtype

(torch.int32, torch.int64)

### Tensor_Operations

In [40]:
ten1 = torch.tensor([1,2,3])
ten2 = torch.tensor([4,5,6])

ten1+ten2

tensor([5, 7, 9])

In [41]:
ten1.shape

torch.Size([3])

In [42]:
ten2*ten1

tensor([ 4, 10, 18])

In [43]:
torch.add(ten1,ten2)

tensor([5, 7, 9])

In [44]:
torch.sub(ten2,ten1), torch.subtract(ten2,ten1)

(tensor([3, 3, 3]), tensor([3, 3, 3]))

In [45]:
ten1*10

tensor([10, 20, 30])

### Tensor Operation in Deep Learning- Matrix Multiplication

In [46]:
# Rules of Matrix Multiplication

# (3,2) * (3,2) = Error
# (4,3) * (3,2) = (4,2)
# (2,2) * (2,5) = (2,5)

torch.matmul(ten2,ten1)

tensor(32)

In [47]:
matrix1 = np.arange(1,13)
matrix1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
matrix4_3 = matrix1.reshape(4,3)
matrix4_3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
matrix4_3 = torch.tensor(matrix4_3)
matrix4_3

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)

In [50]:
target = matrix4_3.view(3, 4)
target

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)

In [51]:
matrix4_3.shape

torch.Size([4, 3])

In [52]:
matrix4_3.dtype

torch.int32

In [53]:
matrix4_3.ndim

2

In [54]:
matrix4_3.size

<function Tensor.size>

#### Transposed

In [55]:
# Transposed
matrix4_3.T

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]], dtype=torch.int32)

In [56]:
matrix4_3.shape

torch.Size([4, 3])

##### matrix3_2

In [57]:
matrix2 = np.arange(1,7)

matrix2

array([1, 2, 3, 4, 5, 6])

In [58]:
matrix3_2 = matrix2.reshape(3,2)
matrix3_2  = torch.tensor(matrix3_2 )   # torch.from_numpy (matrix3_2 )
matrix3_2

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [59]:
matrix3_2.shape

torch.Size([3, 2])

In [60]:
matrix3_2.ndim

2

In [61]:
result = torch.matmul(matrix4_3, matrix3_2)
result.shape

torch.Size([4, 2])

In [62]:
result = torch.mm(matrix4_3, matrix3_2)
result.shape

torch.Size([4, 2])

In [63]:
result


tensor([[ 22,  28],
        [ 49,  64],
        [ 76, 100],
        [103, 136]], dtype=torch.int32)

In [64]:
torch.t(matrix4_3)

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]], dtype=torch.int32)

### Extra_PyTorch_operations_based_on_Tensor_Shape


- Zeros
- Ones
- Random
- Full

In [65]:
tensorZeroes = torch.zeros((3,3))
tensorZeroes

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [66]:
tensorOnes = torch.ones((3,3))
tensorOnes

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [67]:
tensorRandomN = torch.randn((3,2))   # #includes negative tensors
tensorRandomN

tensor([[ 0.8737,  1.4215],
        [-0.6676, -1.7281],
        [ 0.0534,  1.0346]])

In [68]:
tensorRandom = torch.rand((3,3)) #includes only positive tensors
tensorRandom

tensor([[0.5161, 0.1376, 0.1510],
        [0.1570, 0.4623, 0.3033],
        [0.4125, 0.8649, 0.4291]])

In [69]:
customFill = torch.full((3,3),5)
customFill

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [70]:
customFill.shape


torch.Size([3, 3])

In [71]:
customFill.ndim

2

In [72]:
initialFill = torch.full((3,3),0.01)
initialFill

tensor([[0.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 0.0100]])